// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ6uAcmWL3JF-EYlSfln0t58sQS4GhE5E',
    appId: '1:795692228809:web:ec27e0a3198fc3b7bb2d18',
    messagingSenderId: '795692228809',
    projectId: 'yo1eb1bbk73987wbjimgktmu6wt50z',
    authDomain: 'yo1eb1bbk73987wbjimgktmu6wt50z.firebaseapp.com',
    storageBucket: 'yo1eb1bbk73987wbjimgktmu6wt50z.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3iDwOklMqjIYV8O7rB1F2-KzuexDamk',
    appId: '1:795692228809:android:1271eafd79265975bb2d18',
    messagingSenderId: '795692228809',
    projectId: 'yo1eb1bbk73987wbjimgktmu6wt50z',
    storageBucket: 'yo1eb1bbk73987wbjimgktmu6wt50z.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Q2NiLQ8snQa8m2Ialm_xBabDuuFKgvU',
    appId: '1:795692228809:ios:445477d36c8cea77bb2d18',
    messagingSenderId: '795692228809',
    projectId: 'yo1eb1bbk73987wbjimgktmu6wt50z',
    storageBucket: 'yo1eb1bbk73987wbjimgktmu6wt50z.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
